-- Domain: product_catalog
-- Owner: retailpulses/RPagentOS
-- Affected: fix local auth identities for catalog sync
-- Change class: additive
-- Hosted write required: no
-- Consumers: retailpulses/ticket-handling
--
-- Shared hosted-history alignment artifact.
-- Canonical migration:
-- retailpulses/RPagentOS/supabase/migrations/20260717120000_fix_local_auth_identities.sql
-- Reconciliation: retailpulses/RPagentOS#32
--
-- Applied to the shared hosted Supabase project.
-- This file intentionally contains no executable SQL.
