-- Domain: product_catalog
-- Owner: retailpulses/RPagentOS
-- Affected: COALESCE guards for catalogsync_marketplace_projection_v1
-- Change class: additive
-- Hosted write required: no
-- Consumers: retailpulses/ticket-handling
--
-- Shared hosted-history alignment artifact.
-- Canonical migration:
-- retailpulses/RPagentOS/supabase/migrations/20260717130000_fix_projection_null_coalesce.sql
-- Reconciliation: retailpulses/RPagentOS#32
--
-- Applied to the shared hosted Supabase project.
-- This file intentionally contains no executable SQL.
