// ── AI Copywrite Context Builder ──────────────────────────────────
//
// Pure functions that take raw order data + messages and produce
// structured context for LLM prompt assembly and human-readable logging.
//
// Exports:
//   buildContext(orderRow, messages, options) → context object
//   renderContextForPrompt(context) → string (compact, LLM-optimized)
//   renderContextForLog(context, generationMeta) → string (structured log entry)
//
// Separated from the handler so context quality is independently
// testable and reusable (e.g. for batch auto-draft later).
// ──────────────────────────────────────────────────────────────────

import { ORDER_STATUS, REVIEW_STATUS } from "./order-state.mjs";

/**
 * Build a structured context object from an order row and message history.
 *
 * @param {Object} orderRow - Baserow sales row (user_field_names=true shape)
 * @param {Array}  messages  - [{ role, message, createdAt }, ...] from KV/relay
 * @param {Object} [options]
 * @param {string} [options.shopLabel] - human-readable shop name
 * @returns {Object} context object
 */
export function buildContext(orderRow, messages = [], options = {}) {
  const text = (v) => (v != null ? String(v).trim() : "");
  const customerName =
    text(orderRow?.shipping_name) ||
    text(orderRow?.buyer_name) ||
    text(orderRow?.customer_name) ||
    "お客様";
  const productName = text(orderRow?.product_name) || "(商品名なし)";
  const productCode = text(orderRow?.product_code) || "";
  const orderId = text(orderRow?.order_id);
  const shopLabel = text(options.shopLabel) || text(orderRow?.shop_id) || "unknown";

  // Map Baserow select values to JST labels
  const orderStatusRaw = text(orderRow?.order_status) || "";
  const orderStatus = mapOrderStatusLabel(orderStatusRaw);

  // Format message history chronologically (oldest first)
  const messageHistory = (messages || []).map((m) => ({
    role: (m.role || "").toUpperCase() === "BUYER" ? "お客様" : "運営",
    text: text(m.message),
    ts: formatMessageTs(m.createdAt),
  }));

  // Latest customer message
  const buyerMessages = messageHistory.filter((m) => m.role === "お客様");
  const latestCustomerMessage = buyerMessages.length > 0
    ? buyerMessages[buyerMessages.length - 1].text
    : "";

  return {
    customerName,
    productName,
    productCode,
    orderStatus,
    orderId,
    shopLabel,
    messageHistory,
    messageCount: messageHistory.length,
    latestCustomerMessage,
  };
}

/**
 * Render context as a compact string for the LLM user message.
 * Optimized for prompt token efficiency while keeping all key info.
 * Renders polish-mode instructions for the operator's draft.
 *
 * @param {Object} ctx - context object from buildContext()
 * @param {string} [draftText] - optional operator draft to polish
 * @returns {string}
 */
export function renderContextForPrompt(ctx, draftText) {
  const parts = [];
  parts.push("【お客様情報】");
  parts.push(`お名前: ${ctx.customerName}`);
  parts.push(`注文商品: ${ctx.productName}`);
  if (ctx.productCode) parts.push(`商品コード: ${ctx.productCode}`);
  parts.push(`注文ステータス: ${ctx.orderStatus}`);
  parts.push(`注文ID: ${ctx.orderId}`);
  parts.push("");

  const draft = draftText ? String(draftText).trim() : "";
  parts.push("【運営者の下書き】");
  parts.push(draft);
  parts.push("");
  parts.push("上記の運営者による下書きを、日本語ECカスタマーサポートとしてふさわしい形に校正・添削してください。");
  parts.push("内容や意図は変更せず、敬語や表現を自然で丁寧なものに修正してください。");

  return parts.join("\n");
}

/**
 * Render a structured log entry for the AI copywrite log field.
 * Prepended (newest first) to the existing field content.
 *
 * @param {Object} ctx - context object from buildContext()
 * @param {Object} meta - generation metadata
 * @param {string} meta.generatedAt - JST ISO timestamp
 * @param {string} meta.model - e.g. "gpt-4o"
 * @param {number} meta.temperature
 * @param {Object} meta.usage - { prompt_tokens, completion_tokens, total_tokens }
 * @param {string} meta.generatedBy - operator name
 * @param {string} meta.draft - generated reply text
 * @returns {string}
 */
export function renderContextForLog(ctx, meta = {}) {
  const lines = [];
  const sep = "──";
  const pad = (s, n) => String(s || "").padEnd(n);

  lines.push(`${sep} AI Copywrite Log ${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}`);
  lines.push(`Generated: ${meta.generatedAt || ""}`);
  lines.push(`Model: ${meta.model || "?"} | Temp: ${meta.temperature ?? "?"} | Tokens: in=${meta.usage?.prompt_tokens ?? "?"} out=${meta.usage?.completion_tokens ?? "?"} total=${meta.usage?.total_tokens ?? "?"}`);
  lines.push(`Generated by: ${meta.generatedBy || "unknown"}`);
  lines.push("");

  lines.push(`${sep} Context ${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}`);
  lines.push(`Customer: ${ctx.customerName}`);
  const productLine = ctx.productCode
    ? `Product: ${ctx.productName} (${ctx.productCode})`
    : `Product: ${ctx.productName}`;
  lines.push(productLine);
  lines.push(`Order Status: ${ctx.orderStatus} | Order: ${ctx.orderId}`);
  lines.push(`Shop: ${ctx.shopLabel}`);
  lines.push("");
  lines.push(`Messages (${ctx.messageCount} total):`);

  for (const m of ctx.messageHistory) {
    lines.push(`[${m.role}] ${m.ts || ""}`);
    if (m.text) {
      // Split multi-line messages so each line is indented consistently
      for (const sub of m.text.split("\n")) {
        lines.push(sub);
      }
    }
  }
  lines.push("");

  lines.push(`${sep} Generated Draft ${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}`);
  if (meta.draft) {
    for (const sub of String(meta.draft).split("\n")) {
      lines.push(sub);
    }
  } else {
    lines.push("(empty)");
  }
  lines.push("");

  lines.push(`${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}${sep}`);

  return lines.join("\n");
}

// ── Internal helpers ─────────────────────────────────────────────

/**
 * Map Raw Baserow select value to Japanese label for display.
 */
function mapOrderStatusLabel(raw) {
  const map = {
    [ORDER_STATUS.WAITING_FOR_SHIPPING]: "発送待ち",
    [ORDER_STATUS.WAITING_FOR_PAYMENT]: "入金待ち",
    [ORDER_STATUS.COMPLETED]: "完了",
    [ORDER_STATUS.CANCELED]: "キャンセル",
    "Shipped": "発送済み",
    "Pending": "保留中",
  };
  return map[raw] || raw || "不明";
}

/**
 * Format a message createdAt value to "YYYY-MM-DD HH:mm" JST string.
 * Handles ISO strings, Date objects, and null/undefined.
 */
function formatMessageTs(createdAt) {
  if (!createdAt) return "";
  try {
    const d = new Date(createdAt);
    if (Number.isNaN(d.getTime())) return String(createdAt);
    // Use Intl for JST formatting
    const parts = new Intl.DateTimeFormat("en-US", {
      timeZone: "Asia/Tokyo",
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    }).formatToParts(d);
    const map = Object.fromEntries(parts.map((p) => [p.type, p.value]));
    return `${map.year}-${map.month}-${map.day} ${map.hour}:${map.minute}`;
  } catch (_) {
    return String(createdAt);
  }
}
